export const selectUser = (state) => state.auth.user;
export const selectToken = (state) => state.auth.token;
export const selectIsLoggedIn = (state) => state.auth.isLoggedIn;
export const selectIsRefreshing = (state) => state.auth.isRefreshing;
export const selectIsLoading = (state) => state.auth.isLoading;
export const selectIsError = (state) => state.auth.isError;
export const selectUserBalance = (state) => state.auth.user.balance;
export const selectUserEmail = (state) => state.auth.user.email;
export const selectUserName = (state) => state.auth.user.username;
